--- #YAML:1.0
name:                DCOP-Amarok
version:             0.036
abstract:            ~
license:             ~
author:              
    - Juan C. Müller <jcmuller@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DCOP:                          0.036
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
